server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.80.128:3306/student-bv?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    locations: classpath:flyway
mybatis:
  mapper-locations: classpath:mapper/**.xml

